name: youtube_results
description: "Youtube Results is a Dart package designed to help developers easily fetch YouTube search results, videos, channels, playlists, and more using the YouTube Data API. This package provides simple and efficient methods to access a variety of YouTube content, including detailed video information, channel stats, playlist data, and suggestions based on search queries."
version: 0.0.1
homepage: https://github.com/JonathanGech/youtube_results
repository: https://github.com/JonathanGech/youtube_results.git

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  xml2json: ^5.3.3
  collection: ^1.16.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
