name: youtube_results
description: "youtube_results is a lightweight Flutter & Dart package for fetching YouTube search results, videos, Shorts, channels, playlists, and related videos via the YouTube Data API."
version: 0.1.0
homepage: https://github.com/JonathanGech/youtube_results
repository: https://github.com/JonathanGech/youtube_results.git

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  html: ^0.15.0
  xml2json: ^6.2.6
  collection: ^1.18.0
  http: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
